{% set name = "enstat" %}
{% set org = "tdegeus" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 71ce0e0d5de98e70aa2eff3a61cd9172d7b57014d6c81a05cf3aa5cf7ffc68e9

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3
    - setuptools_scm
  run:
    - numpy
    - python >=3

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Iterative ensemble averages
  description: Iterative ensemble averages
  doc_url: https://github.com/{{ org }}/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
